from typing import List
from config.db_config import DBConnectionHandler
from models.model import Orders, OrderDetails

class OrderDAO:
    def inserir_pedido(self, pedido: Orders, detalhes: List[OrderDetails]) -> bool:
        try:
            with DBConnectionHandler() as db:
                db.session.add(pedido)
                db.session.flush()

                for detalhe in detalhes:
                    detalhe.orderid = pedido.orderid
                    db.session.add(detalhe)

                db.session.commit()
                return True
        except Exception as e:
            print(f"Erro ao inserir pedido: {e}")
            return False

## ATENÇÃO: Será necessário alterar a coluna orderid da tabela orders para autoincrementar IDs.
## Execute no PostgreSQL:
## ALTER TABLE northwind.orders
## ALTER COLUMN orderid ADD GENERATED BY DEFAULT AS IDENTITY;
## Isso acontece porque o mapeamento espera que o banco autoincremente os ids, mas atualmente ele não está configurado desta forma